### ISSUE TITLE
Add build guide and update the image name

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/vcuda-controller#1]
**Describe the bug**

1. There is no build guide in README
2. The build result is the docker image, which is called: `tkestack.io/gaia/vcuda`, need to modify

**Environment**
 - OS: Linux VM_149_11_centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
 - golang: go version go1.12.4 linux/amd64

**Comment by mYmNeo** [comment]
`tkestack.io/gaia/vcuda` is just an image tag name, you can change it to any name which matches the repository valid pattern.
This project is very simple,  only to run the only one script `build-img.sh`
