### ISSUE TITLE
Which GPU are you using ?

### ISSUE THREAD

**Issue by xiazhiyi99** [tkestack/vcuda-controller#13]
Hi! Thanks for the great working. I'm using Tesla T4 to test gpu-manager and get low GPU utilization. I found you mention modification according to GPU in https://github.com/tkestack/vcuda-controller/issues/12. So I wonder which gpu you are using?

**Comment by mYmNeo** [comment]
We use M40/P40 in the paper.

**Comment by xiazhiyi99** [comment]
> We use M40/P40 in the paper.

Thanks for the reply! Closing this issue.
