### ISSUE TITLE
Doubts about cuArray3DCreate_helper calculating memory usage

### ISSUE THREAD

**Issue by pidb** [tkestack/vcuda-controller#18]
I see the function 

https://github.com/tkestack/vcuda-controller/blob/5ec3fcbc58679bbbbd82ef9e21d647d8d7383876/src/hijack_call.c#L713-L731

so, should it be change to 
```c
    request_size = base_size * pAllocateArray->NumChannels *
                   pAllocateArray->Height * pAllocateArray->Width * pAllocateArray->Depth;

```

**Comment by mYmNeo** [comment]
> I see the function
> 
> https://github.com/tkestack/vcuda-controller/blob/5ec3fcbc58679bbbbd82ef9e21d647d8d7383876/src/hijack_call.c#L713-L731
> 
> so, should it be change to
> 
> ```c
>     request_size = base_size * pAllocateArray->NumChannels *
>                    pAllocateArray->Height * pAllocateArray->Width * pAllocateArray->Depth;
> ```

I'm not familiar with this api, maybe the calculation of memory is wrong, could you help to validate this?

**Comment by algebra2k** [comment]
> > I see the function
> > https://github.com/tkestack/vcuda-controller/blob/5ec3fcbc58679bbbbd82ef9e21d647d8d7383876/src/hijack_call.c#L713-L731
> > 
> > so, should it be change to
> > ```c
> >     request_size = base_size * pAllocateArray->NumChannels *
> >                    pAllocateArray->Height * pAllocateArray->Width * pAllocateArray->Depth;
> > ```
> 
> I'm not familiar with this api, maybe the calculation of memory is wrong, could you help to validate this?



> > I see the function
> > https://github.com/tkestack/vcuda-controller/blob/5ec3fcbc58679bbbbd82ef9e21d647d8d7383876/src/hijack_call.c#L713-L731
> > 
> > so, should it be change to
> > ```c
> >     request_size = base_size * pAllocateArray->NumChannels *
> >                    pAllocateArray->Height * pAllocateArray->Width * pAllocateArray->Depth;
> > ```
> 
> I'm not familiar with this api, maybe the calculation of memory is wrong, could you help to validate this?

Of course, I will verify and try to fix it later.

**Comment by mYmNeo** [comment]
#28
