### ISSUE TITLE
some issues on cuda-11.4

### ISSUE THREAD

**Issue by M201972777** [tkestack/vcuda-controller#20]
I want to ask some question, and look forward to your reply. 
Cugetprocaddress is added in cuda-11.4, which can prevent our hijacking code from being executed. Have you solved this problem? If so, how?

**Comment by work-chausat** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff687ea02 in cuGetProcAddress (symbol=0x4714d8 "cuGetProcAddress", pfn=0x7fffffffdeb8, cudaVersion=11030, flags=0) at /home/jdos/vcuda-controller/src/hijack_call.c:1030
#2  0x0000000000418070 in __cudart523 ()
#3  0x0000000000420bb7 in __cudart514 ()
#4  0x0000000000420c98 in __cudart1325 ()
#5  0x00007ffff79b7dd7 in __pthread_once_slow (once_control=0x69b150 <__cudart2781>, init_routine=0x420c50 <__cudart1325>) at pthread_once.c:116
#6  0x000000000046ab89 in __cudart1597 ()
#7  0x0000000000417a47 in __cudart512 ()
#8  0x0000000000444086 in cudaMalloc ()
#9  0x0000000000403de1 in cudaMalloc<float> (devPtr=0x7fffffffe110, size=512) at /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:608
#10 0x0000000000403a61 in distanceArray (out=0x6ae2b0, in=0x6ae0a0, ref=0.5, len=128) at kernel.cu:27

**Comment by hzliangbin** [comment]
@work-chausat did you solve it?

**Comment by mYmNeo** [comment]
#30
