### ISSUE TITLE
how to view  logs output by vcuda-controller

### ISSUE THREAD

**Issue by hzliangbin** [tkestack/vcuda-controller#27]
I've noticed that vcuda-controller is compiled into .so library, and it is mounted to pod which uses GPU. 

Also, some logs is printed to stderr. But how can i check the logs. I set "LOGGER_LEVEL" to "6" as an env of the pod, make no sense.

**Comment by hzliangbin** [comment]
@mYmNeo PTAL, thanks a lot.

**Comment by seanchen022** [comment]
> I've noticed that vcuda-controller is compiled into .so library, and it is mounted to pod which uses GPU.
> 
> Also, some logs is printed to stderr. But how can i check the logs. I set "LOGGER_LEVEL" to "6" as an env of the pod, make no sense.

hi,did you solve the problem?
