### ISSUE TITLE
CUBLAS_STATUS_ALLOC_FAILED (cuda11.4.4，cuBLAS 11.6.5.2)

### ISSUE THREAD

**Issue by work-chausat** [tkestack/vcuda-controller#33]
当上层调用cublasCreate的时候，程序会alloc失败，报：CUBLAS_STATUS_ALLOC_FAILE

**Comment by hzliangbin** [comment]
@work-chausat could you try this [commit](https://github.com/tkestack/vcuda-controller/pull/32/commits/c19c5474dff013c7a774a0fc76da4cf6abdfebb6)? We've encountered similar problem, and fixed it.

**Comment by work-chausat** [comment]
> @work-chausat could you try this [commit](https://github.com/tkestack/vcuda-controller/pull/32/commits/c19c5474dff013c7a774a0fc76da4cf6abdfebb6)? We've encountered similar problem, and fixed it.

好的，我测试一下。

**Comment by work-chausat** [comment]
> @work-chausat could you try this [commit](https://github.com/tkestack/vcuda-controller/pull/32/commits/c19c5474dff013c7a774a0fc76da4cf6abdfebb6)? We've encountered similar problem, and fixed it.

@hzliangbin @VincentLeeMax @mYmNeo 算力控制不住，gpu拆分失败。如下图算力设置为整卡20%，但实际利用率 top_result.user_current已到整卡99%

<img width="639" alt="截屏2022-11-18 16 17 59" src="https://user-images.githubusercontent.com/29337670/202654806-6351c048-c383-4825-aa8d-d2fddf001266.png">

**Comment by hzliangbin** [comment]
@work-chausat how about GPU memory ？is it isolated？
